### ISSUE TITLE
解码过程中频繁报以下错误，请问应该如何处理？

### ISSUE THREAD

**Issue by hyqinglan** [saucer-man/qq_msg_decode#2]
Traceback (most recent call last):
  File "D:\qq_msg_decode-main\index.py", line 387, in <module>
    run(db_path)
  File "D:\qq_msg_decode-main\index.py", line 358, in run
    msg = Unpack(msg_content)
          ^^^^^^^^^^^^^^^^^^^
  File "D:\qq_msg_decode-main\index.py", line 297, in Unpack
    msg.SenderNickname = DecodeNickname(v)
                         ^^^^^^^^^^^^^^^^^
  File "D:\qq_msg_decode-main\index.py", line 99, in DecodeNickname
    while not buf.empty():
              ^^^^^^^^^^^
  File "D:\qq_msg_decode-main\index.py", line 27, in empty
    return len(self.buf) <= self.off
           ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

谢谢指教！

**Comment by saucer-man** [comment]
在这里 加一行判断吧

**Comment by hyqinglan** [comment]
谢谢思路，已经搞定了
